# Generated by Django 2.2.2 on 2019-06-27 09:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actors', models.CharField(max_length=200)),
                ('awards', models.CharField(max_length=200)),
                ('box_office', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('dvd', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('metascore', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('plot', models.CharField(max_length=1000)),
                ('poster', models.CharField(max_length=200)),
                ('production', models.CharField(max_length=200)),
                ('rated', models.CharField(max_length=200)),
                ('released', models.DateField()),
                ('runtime', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('imdb_id', models.CharField(max_length=200)),
                ('imdb_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('imdb_votes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='moviesapp.Movie')),
            ],
            options={
                'ordering': ['source'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='moviesapp.Movie')),
            ],
            options={
                'ordering': ['movie', 'created_at'],
            },
        ),
    ]
